#!/bin/sh
cd /opt/www/comnovo.com/Daemons/ServerJobs
#QUEUE=email VERBOSE=True PIDFILE=/tmp/worker_comnovo_email.pid /opt/iapps/php/bin/php -f /opt/www/comnovo.com/Daemons/ServerJobs/Resque.init.php email > /tmp/worker_comnovo_email.log
QUEUE=email VERBOSE=True PIDFILE=/tmp/worker_comnovo_email.pid /opt/iapps/php/bin/php -f /opt/www/comnovo.com/Daemons/ServerJobs/Resque.init.php email
